export const ROUTE_PROXIES_CREATE = 'ROUTE_PROXIES_CREATE';
export const ROUTE_PROXIES_LIST = 'ROUTE_PROXIES_LIST';
export const ROUTE_PROXIES_DELETE = 'ROUTE_PROXIES_DELETE';
export const ROUTE_PROXIES_UPDATE = 'ROUTE_PROXIES_UPDATE';
export const ROUTE_PROXIES_IMPORT = 'ROUTE_PROXIES_IMPORT';
