export const PROXIES_EXAMPLE = 'PROXIES_EXAMPLE';
export const PROXIES_CREATE = 'PROXIES_CREATE';
export const PROXIES_LIST = 'PROXIES_LIST';
export const PROXIES_DELETE = 'PROXIES_DELETE';
export const PROXIES_UPDATE = 'PROXIES_DELETE';
export const PROXIES_IMPORT = 'PROXIES_IMPORT';
