module.exports = {
    ROUTE_PROXIES_CREATE: 'ROUTE_PROXIES_CREATE',
    ROUTE_PROXIES_LIST: 'ROUTE_PROXIES_LIST',
    ROUTE_PROXIES_DELETE: 'ROUTE_PROXIES_DELETE',
    ROUTE_PROXIES_UPDATE: 'ROUTE_PROXIES_UPDATE',
    ROUTE_PROXIES_IMPORT: 'ROUTE_PROXIES_IMPORT',
};
